namespace: "prod"


serviceAccount:
  create: true
  name: "nginx-ingress-serviceaccount"

global:
    registry: ''


istio:
    enabled: false

java:
    options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom


frontend:
    replicas: 1
    image:
        repo: weaveworksdemos/front-end
        tag: 0.3.12
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi
