namespace: "prod"
serviceAccount:
  create: true
  name: "nginx-ingress-serviceaccount"

controller:
  admissionWebhooks:
    enabled: false

global:
    registry: ''

java:
    options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom

istio:
    enabled: false

ingress:
    enabled: true
    className: "nginx"
    annotations:
        kubernetes.io/ingress.class: nginx
    labels: {}
    hosts:
    - host: 'sock-shop-prod.zennon.link'
    paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: front-end
              port:
                number: 8079
    tls:                             
    - hosts:
        - sock-shop.zennon.link
    secretName: tls-secret-name
