namespace: "dev"

serviceAccount:
  create: false
  name: "aws-load-balancer-controller"

controller:
  admissionWebhooks:
    enabled: false

global:
  registry: ''

java:
  options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom

istio:
  enabled: false

# Ingress Configuration
ingress:
  enabled: true
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:715841363614:certificate/636f4b75-129c-43f0-ac85-22a162946974
  host: sock-shop-dev.zennon.link
  serviceName: front-end
  servicePort: 8079