namespace: dev
clusterName: SockShop-eks   # Remplace par ton nom de cluster EKS
region: eu-west-1              # Remplace par ta région AWS (ex : us-west-2)
vpcId: vpc-0708985fb5c18eb4c            # Remplace par l'ID de ton VPC AWS

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  #namespace: kube-system

#image:
#  repository: amazon/aws-alb-ingress-controller
#  tag: latest                    # Remplace par la dernière version disponible

#extraArgs:
#  cluster-name: Sockshop-eks    # Remplace par ton nom de cluster EK
#  ingress-class: alb
#