namespace: dev
global:
    registry: ''


istio:
    enabled: false

ordersdb:
    image:
        repo: mongo
        tag: 4.4.0
    resources:
        requests:
            cpu: 500m
            memory: 512Mi
        limits:
            cpu: 500m
            memory: 512Mi
    persistentVolume:
        storageClass: ''
        size: 512Mi

orders:
    image:
        repo: weaveworksdemos/orders
        tag: 0.4.7
    containerPort: 80
    resources:
        limits:
            cpu: 500m
            memory: 2000Mi
        requests:
            cpu: 200m
            memory: 2000Mi

zipkin:
    image:
        repo: openzipkin/zipkin
        tag: 2.21
    resources:
        limits:
            cpu: 300m
            memory: 1000Mi
        requests:
            cpu: 100m
            memory: 300Mi
    enabled:  false
    url: zipkin.zipkin.svc.cluster.local

java:
    options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
