---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      name: catalogue
  template:
    metadata:
      labels:
        name: catalogue
      annotations:
        {{- if .Values.istio.enabled }}
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        {{- end }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"             # Ajuste le chemin si nécessaire
        prometheus.io/port: "{{ .Values.catalogue.containerPort }}"  # Port exposant les métriques
    spec:
      containers:
      - name: catalogue
        image: 715841363614.dkr.ecr.eu-west-1.amazonaws.com/sock-shop-catalogue:latest 
        command: ["/app"]
        args:
        - -port={{ .Values.catalogue.containerPort }}
        - -DSN=catalogue_user:default_password@tcp(catalogue-db.{{ .Release.Namespace }}.svc.cluster.local:3306)/socksdb
        {{- if .Values.zipkin.enabled }}
        env:
         - name: ZIPKIN
           value: http://{{ .Values.zipkin.url }}:9411/api/v1/spans
        {{- end }}
        resources:
{{ toYaml .Values.catalogue.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.catalogue.containerPort }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
{{- if lt (int .Values.carts.containerPort) 1024 }}
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
{{- end }}
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.catalogue.containerPort }}
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.catalogue.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
