---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-end
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: front-end

  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
    
