---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8079
    #nodePort: 30001
  selector:
    name: front-end

