apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-load-balancer-controller-binding-2
  namespace: dev
  labels:
    app.kubernetes.io/managed-by: Helm  # Ajoutez ce label
  annotations:
    meta.helm.sh/release-name: ingress  # Ajoutez cette annotation
    meta.helm.sh/release-namespace: dev  # Ajoutez cette annotation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-load-balancer-controller-2
subjects:
  - kind: ServiceAccount
    name: aws-load-balancer-controller-2
    namespace: dev
