apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller-2
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::715841363614:role/AWSServiceRoleForElasticLoadBalancing
    #meta.helm.sh/release-name: ingress  # Ajoutez cette annotation
    #meta.helm.sh/release-namespace: kube-system  # Ajoutez cette annotation
